name: sharedkits
description: Shared utilities for personal Flutter projects
version: 0.0.1
homepage: https://github.com/Elijah-Ashitey/flutter-util/tree/main
publish_to: 'https://github.com/Elijah-Ashitey/flutter-util.git'

environment:
  sdk: '>=3.3.2 <4.0.0'
  # flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_staggered_animations: ^1.1.1
  flutter_multi_formatter: ^2.12.8
  flutter_tabler_icons: ^1.26.0
  cached_network_image: ^3.3.1
  modal_bottom_sheet: ^3.0.0
  simple_animations: ^5.0.2
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.10+1
  feather_icons: ^1.2.0
  google_fonts: ^6.2.1
  copy_with_extension:
  fluttericon: ^2.0.0
  local_auth: ^2.2.0
  equatable: ^2.0.5
  filesize: ^2.0.1
  logger: ^2.2.0
  lottie: ^3.1.0
  mime: ^1.0.4
  bloc: ^8.1.4
  intl: 
  wtf_sliding_sheet: ^1.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner:
  json_serializable:
  copy_with_extension_gen:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
